import java.util.*;
import java.time.LocalDate;
class OnlineBookStory {
	public static void main(String[] args){
		Scanner input = new Scanner(System.in);
   /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	double CR_Book = 80.00;
	double Pen = 20.00;
	double Pencil = 15.00;
	double Eraser = 10.00;
	double Glue = 40.00;
	double Pencil_Box = 100.00;
	double Water_Bottle = 230.00;
	double Lunch_Box = 250.00;
	double Calculator = 250.00;
	double School_Bag = 1000.00;
	double Ruler = 10.00;
	double Highlighter = 50.00;
	double Cardboard_File = 25.00;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	System.out.println(" ");
	System.out.println("\t\t\t\t______             _      _____ _                  ");
	System.out.println("\t\t\t\t| ___ \\           | |    /  ___| |                 ");
	System.out.println("\t\t\t\t| |_/ / ___   ___ | | __ \\ `--.| |__   ___  _ __   ");
	System.out.println("\t\t\t\t| ___ \\/ _ \\ / _ \\| |/ /  `--. \\ '_ \\ / _ \\| '_ \\  ");
	System.out.println("\t\t\t\t| |_/ / (_) | (_) |   <  /\\__/ / | | | (_) | |_) | ");
	System.out.println("\t\t\t\t\\____/ \\___/ \\___/|_|\\_\\ \\____/|_| |_|\\___/| .__/  ");
	System.out.println("\t\t\t\t                                           | |     ");
	System.out.println("\t\t\t\t                                           |_|     ");
	System.out.println("\t\t\t\t                                                   ");
	System.out.println("\t\t\t================================================================");
	System.out.println("\n");
	LocalDate myObj = LocalDate.now();
	System.out.print("\t\t\t\tEnter Date\t\t: "+myObj);
	System.out.println("\n");
	System.out.print("\t\t\t\tCustomer Number\t\t: ");
	String cusNumber = input.next();
	System.out.println("\n");
	System.out.print("\t\t\t\tEnter Customer Name\t: ");
	String cusName = input.next();
	System.out.println("\n");
	System.out.println("\n");
	System.out.println("\n");
	System.out.println("\t\t\t\t");
	System.out.println("\t\t\t\t  ____       _                 _   ___ _                      ");
	System.out.println("\t\t\t\t / ___|  ___| |__   ___   ___ | | |_ _| |_ ___ _ __ ___  ___  ");
	System.out.println("\t\t\t\t \\___ \\ / __| '_ \\ / _ \\ / _ \\| |  | || __/ _ \\ '_ ` _ \\/ __| ");
	System.out.println("\t\t\t\t  ___) | (__| | | | (_) | (_) | |  | || ||  __/ | | | | \\__ \\ ");
	System.out.println("\t\t\t\t |____/ \\___|_| |_|\\___/ \\___/|_| |___|\\__\\___|_| |_| |_|___/ ");
	System.out.println("\t\t\t\t                                                              ");
	System.out.println("\t\t\t============================================================================");
	System.out.println("\n");
	System.out.print("\t\t\t\tCR Book (QTY)  \t\t: ");
	int crbookQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tPen (QTY) \t\t: ");
	int penQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tPencil (QTY) \t\t: ");
	int pencilQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tEraser (QTY) \t\t: ");
	int eraserQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tPencil Box (QTY) \t: ");
	int pencilboxQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tGlue Bottle (QTY) \t: ");
	int gluebottleQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tRuler- (MEDIUM) (QTY) \t: ");
	int rullerQty = input.nextInt();
	System.out.println("\n");
	System.out.println("\n");
	System.out.println("\t\t\t\t");
	System.out.println("\t\t\t\t   ___   __  __ _            ___ _                      ");
	System.out.println("\t\t\t\t  / _ \\ / _|/ _(_) ___ ___  |_ _| |_ ___ _ __ ___  ___  ");
	System.out.println("\t\t\t\t | | | | |_| |_| |/ __/ _ \\  | || __/ _ \\ '_ ` _ \\/ __| ");
	System.out.println("\t\t\t\t | |_| |  _|  _| | (_|  __/  | || ||  __/ | | | | \\__ \\ ");
	System.out.println("\t\t\t\t  \\___/|_| |_| |_|\\___\\___| |___|\\__\\___|_| |_| |_|___/ ");
	System.out.println("\t\t\t\t                                                        ");
	System.out.println("\t\t\t\t");
	System.out.println("\t\t\t============================================================================");
	System.out.println("\n");
	System.out.print("\t\t\t\tCalculator (QTY)    : ");
	int calculatorQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tHighlighters (QTY)  : ");
	int highlightersQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tCarboard File (QTY) : ");
	int carboardfileQty = input.nextInt();
	System.out.println("\n");
	System.out.println("\n");
	System.out.println("\t\t\t\t");
	System.out.println("\t\t\t\t   ___  _   _                 ___ _                      ");
	System.out.println("\t\t\t\t  / _ \\| |_| |__   ___ _ __  |_ _| |_ ___ _ __ ___  ___  ");
	System.out.println("\t\t\t\t | | | | __| '_ \\ / _ \\ '__|  | || __/ _ \\ '_ ` _ \\/ __| ");
	System.out.println("\t\t\t\t | |_| | |_| | | |  __/ |     | || ||  __/ | | | | \\__ \\ ");
	System.out.println("\t\t\t\t  \\___/ \\__|_| |_|\\___|_|    |___|\\__\\___|_| |_| |_|___/ ");
	System.out.println("\t\t\t\t                                                         ");
	System.out.println("\t\t\t\t");
	System.out.println("\t\t\t============================================================================");
	System.out.println("\n");
	System.out.print("\t\t\t\tWater Bottle (QTY)    : ");
	int waterbottleQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tLunch Box (QTY)  : ");
	int lunchboxQty = input.nextInt();
	System.out.println("\n");
	System.out.print("\t\t\t\tSchool Bag (QTY) : ");
	int schoolbagQty = input.nextInt();
	System.out.println("\n");
	System.out.println("\n");
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	double crbookPrice = CR_Book*crbookQty;
	double penPrice = Pen*penQty;
	double pencilPrice = Pencil*pencilQty;
	double eraserPrice = Eraser*eraserQty;
	double gluebottlePrice = Glue*gluebottleQty;
	double pencilboxPrice = Pencil_Box*pencilboxQty;
	double waterbottlePrice = Water_Bottle*waterbottleQty;
	double lunchboxPrice = Lunch_Box*lunchboxQty;
	double calculatorPrice = Calculator*calculatorQty;
	double schoolbagPrice = School_Bag*schoolbagQty;
	double rullerPrice = Ruler*rullerQty;
	double highlightersPrice = Highlighter*highlightersQty;
	double carboardfilePrice = Cardboard_File*carboardfileQty;
	double total = crbookPrice+penPrice+pencilPrice+eraserPrice+gluebottlePrice+
	pencilboxPrice+waterbottlePrice+lunchboxPrice+calculatorPrice+schoolbagPrice+
	rullerPrice+highlightersPrice+carboardfilePrice;
	double discount = (total/100)*10;
	double price = total-discount;
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	System.out.println("+----------------------------------------------------------------------------------------------------------------------+");
	System.out.println("|\t\t\t\t 																											|");
	System.out.println("|\t\t\t\t______             _      _____ _                  														|");
	System.out.println("|\t\t\t\t| ___ \\           | |    /  ___| |                 														|");
	System.out.println("|\t\t\t\t| |_/ / ___   ___ | | __ \\ `--.| |__   ___  _ __   														|");
	System.out.println("|\t\t\t\t| ___ \\/ _ \\ / _ \\| |/ /  `--. \\ '_ \\ / _ \\| '_ \\  													|");
	System.out.println("|\t\t\t\t| |_/ / (_) | (_) |   <  /\\__/ / | | | (_) | |_) | 														|");
	System.out.println("|\t\t\t\t\\____/ \\___/ \\___/|_|\\_\\ \\____/|_| |_|\\___/| .__/  													|");
	System.out.println("|\t\t\t\t                                           | |     														|");
	System.out.println("|\t\t\t\t                                           |_|     														|");
	System.out.println("+----------------------------------------------------------------------------------------------------------------------+");
	System.out.printf("| %-116s |%n","Tel : "+cusNumber);
	System.out.printf("| %-97s  %-2s |%n","Name : "+cusName,"Date : "+myObj);
	System.out.println("+----------------------------------------------------------------------------------------------------------------------+");
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Items","QTY","UnitPrice","Price");
	System.out.println("+----------------------------------------------------------------------------------------------------------------------+");
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","CR Book",crbookQty,CR_Book,crbookPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","pen",penQty,Pen,penPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Pencil",pencilQty,Pencil,pencilPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Erasers",eraserQty,Eraser,eraserPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Glue",gluebottleQty,Glue,gluebottlePrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Pencil Box",pencilboxQty,Pencil_Box,pencilboxPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Water Bottle",waterbottleQty,Water_Bottle,waterbottlePrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Lunch Box",lunchboxQty,Lunch_Box,lunchboxPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Calculator",calculatorQty,Calculator,calculatorPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","School Bag",schoolbagQty,School_Bag,schoolbagPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Ruler",rullerQty,Ruler,rullerPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","Highlighters",highlightersQty,Highlighter,highlightersPrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","CardBord File",carboardfileQty,Cardboard_File,carboardfilePrice);        
	System.out.printf("| %-30s | %-19s | %-29s | %-29s |%n","","","","");        
	System.out.println("+----------------------------------------------------------------------------------------------------------------------+");
	System.out.printf("| %-30s | %-51s | %-29s |%n","","Total",total);               
	System.out.println("|				 |-------------------------------------------------------------------------------------+");
	System.out.printf("| %-30s | %-51s | %-29s |%n","","Discount (10%)",discount);
	System.out.println("|				 |-------------------------------------------------------------------------------------+");
	System.out.printf("| %-30s | %-51s | %-29s |%n","","Price",price);
	System.out.println("+----------------------------------------------------------------------------------------------------------------------+");
	System.out.println("\n");
	System.out.println("\n");
	System.out.println("\t\t\t\t");
	System.out.println("\t\t\t\t  ____        _                       ");
	System.out.println("\t\t\t\t |  _ \\      | |                      ");
	System.out.println("\t\t\t\t | |_) | __ _| | __ _ _ __   ___ ___  ");
	System.out.println("\t\t\t\t |  _ < / _` | |/ _` | '_ \\ / __/ _ \\ ");
	System.out.println("\t\t\t\t | |_) | (_| | | (_| | | | | (_|  __/ ");
	System.out.println("\t\t\t\t |____/ \\__,_|_|\\__,_|_| |_|\\___\\___| ");
	System.out.println("\t\t\t\t                                      ");
	System.out.println("\t\t\t======================================================");
	System.out.println("\n");
	System.out.println("\n");
	System.out.print("Enter Customer given amout : ");
	double amout = input.nextDouble();
	double change = amout-price;
	System.out.println("\n");
	System.out.println("\n");
	System.out.println("				 +-----------------------------------------------------------------+");
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Net Amout",price);
	System.out.println("				 +-----------------------------------------------------------------+");
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Cash",amout);
	System.out.println("				 +-----------------------------------------------------------------+");
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Change",change);
	System.out.println("				 +-----------------------------------------------------------------+");        
	System.out.println("\n");
	System.out.println("\n");
	System.out.println("				 +-----------------------------------------------------------------+");
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Value","No");
	System.out.println("				 +-----------------------------------------------------------------+");
	int Intchange = (int) change;
	int mod = Intchange%5000;
	int note = Intchange/5000;
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Rs.5000",note);
	System.out.println("				 +-----------------------------------------------------------------+");
	note = mod/2000;
	mod = mod%2000;
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Rs.2000",note);       
	System.out.println("				 +-----------------------------------------------------------------+");
	note = mod/1000;
	mod = mod%1000;
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Rs.1000",note);
	System.out.println("				 +-----------------------------------------------------------------+");
	note = mod/500;
	mod = mod%500;
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Rs.500",note);
	System.out.println("				 +-----------------------------------------------------------------+");
	note = mod/200;
	mod = mod%200;
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Rs.200",note);
	System.out.println("				 +-----------------------------------------------------------------+");        
	note = mod/100;
	mod = mod%100;
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Rs.100",note);
	System.out.println("				 +-----------------------------------------------------------------+");
	note = mod/50;
	mod = mod%50;
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Rs.50",note);
	System.out.println("				 +-----------------------------------------------------------------+");
	note = mod/20;
	mod = mod%20;
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Rs.20",note);
	System.out.println("				 +-----------------------------------------------------------------+");
	note = mod/10;
	mod = mod%10;        
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Coin 10",note);
	System.out.println("				 +-----------------------------------------------------------------+");
	note = mod/5;
	mod = mod%5;
	System.out.printf(" %-31s | %-31s | %-29s |%n","","Coin 5",note);
	System.out.println("				 +-----------------------------------------------------------------+");   
    }
}
